package Telas;

import ClassesTeste.ConectaBanco;
import ClassesTeste.dao.*;
import ClassesTeste.utils.DesfragmentadorBanco;
import ClassesTeste.utils.ManipuladorArquivos;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo
 */
public class JProvas extends javax.swing.JFrame {
 
  static final ConectaBanco conexaoJProvas = new ConectaBanco();
  public static DAOprova JProvas_DAOProva;
  public static DAOquestao JProvas_DAOquestao;
  public static ManipuladorArquivos mp = new ManipuladorArquivos();
  
  URL url = this.getClass().getResource("/Imagens/IconesSistema/JP32.png");  
  Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
  TelaDesfragmentaBanco tela1=new TelaDesfragmentaBanco();
  boolean verTela1=true;

  public JProvas() {
    initComponents();
    subtelaPainelArvore2.tAbas = painelJtab;
    subtelaPainelArvore2.jprovas_telasbtPainelArvore = this;
    this.setTitle("JProvas"); 
    setIconImage(imagemTitulo);
    JProvas_DAOProva = new DAOprova(subtelaPainelArvore2,conexaoJProvas);
    JProvas_DAOquestao = new DAOquestao(subtelaPainelArvore2,conexaoJProvas);
  
  //acao para encerrar o sistema
  this.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        encerrarSistema();
    }
  });
  subtelaPainelArvore2.tAbas.addTab("JPROVAS", subtelaPainelArvore2.jp_logotipo);
  
  }

  public float posicionaEixoXJpanel(){
    float posicaoX=this.getAlignmentX()-10;
    return posicaoX;
  }
  
    public float posicionaEixoYJpanel(){
    float posicaoY=this.getAlignmentY()-10;
    return posicaoY;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel1 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jlabInformativaRodape = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    itemMenu_Configuracoes = new javax.swing.JMenu();
    itemMenu_Desfragmentar = new javax.swing.JMenuItem();
    itemMenu_Preferencias = new javax.swing.JMenuItem();
    itemMenu_Sair = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    itemMenu_Manual = new javax.swing.JMenuItem();
    itemMenu_Sobre = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    subtelaPainelArvore2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botaoAberto.gif"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel1.setText("        JPROVAS - Criador de Provas");

    jlabInformativaRodape.setForeground(new java.awt.Color(51, 51, 255));
    jlabInformativaRodape.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jlabInformativaRodape.setText(".");

    jMenu1.setText("Arquivo");

    itemMenu_Configuracoes.setText("Configurações");

    itemMenu_Desfragmentar.setText("Desfragmentar Banco");
    itemMenu_Desfragmentar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemMenu_DesfragmentarActionPerformed(evt);
      }
    });
    itemMenu_Configuracoes.add(itemMenu_Desfragmentar);

    itemMenu_Preferencias.setText("Preferencias");
    itemMenu_Preferencias.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemMenu_PreferenciasActionPerformed(evt);
      }
    });
    itemMenu_Configuracoes.add(itemMenu_Preferencias);

    jMenu1.add(itemMenu_Configuracoes);

    itemMenu_Sair.setText("Sair");
    itemMenu_Sair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemMenu_SairActionPerformed(evt);
      }
    });
    jMenu1.add(itemMenu_Sair);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Ajuda");

    itemMenu_Manual.setText("Manual de utilização");
    itemMenu_Manual.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemMenu_ManualActionPerformed(evt);
      }
    });
    jMenu2.add(itemMenu_Manual);

    itemMenu_Sobre.setText("Sobre");
    itemMenu_Sobre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemMenu_SobreActionPerformed(evt);
      }
    });
    jMenu2.add(itemMenu_Sobre);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jSeparator2)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(subtelaPainelArvore2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(painelJtab, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlabInformativaRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1)
          .addComponent(painelJtab)
          .addComponent(subtelaPainelArvore2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jlabInformativaRodape)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(verTela1==true){
      subtelaPainelArvore2.setVisible(false);
      //this.remove(painelArvoreFinal1);
      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botaoFechado.gif")));
      this.revalidate();
      verTela1=false;

    }
    else{
      subtelaPainelArvore2.setVisible(true);
      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botaoAberto.gif")));
      this.revalidate();
      verTela1=true;
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void itemMenu_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_SobreActionPerformed
    TelaSobre tSobre2 = new TelaSobre(this,true);
    tSobre2.setVisible(true);
  }//GEN-LAST:event_itemMenu_SobreActionPerformed

  private void itemMenu_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_SairActionPerformed
    encerrarSistema();
  }//GEN-LAST:event_itemMenu_SairActionPerformed

  private void itemMenu_DesfragmentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_DesfragmentarActionPerformed
    int reply = JOptionPane.showConfirmDialog(null, "Será realizado ação para desfragmentar o arquivo de dados. "
                +"Isto pode levar\n alguns minutos, dependendo do tamanho do arquivo atual.\n\n"
                +"Deseja realizar a desfragmentacao do arquivo agora?", "DESFRAGMENTAR ARQUIVO DE DADOS", JOptionPane.YES_NO_OPTION);
    if (reply == JOptionPane.NO_OPTION) {return;}
    DesfragmentadorBanco sistem = new DesfragmentadorBanco();
    sistem.banco1= subtelaPainelArvore2.conexao;
    sistem.exibeMsgFinal=true;
    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    sistem.desfragmentaMDB();
    this.setCursor(Cursor.getDefaultCursor());
  }//GEN-LAST:event_itemMenu_DesfragmentarActionPerformed

    private void itemMenu_PreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_PreferenciasActionPerformed
        TelaPreferencias telaPreferencias = new TelaPreferencias(this,true);
        telaPreferencias.setVisible(true);
    }//GEN-LAST:event_itemMenu_PreferenciasActionPerformed

  private void itemMenu_ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_ManualActionPerformed
    //ABRIR O MANUAL DE UTILIZAÇÃO DO SISTEMA
    if(!mp.verificaDiretorioExiste("HTML")){mp.criarDiretorio("HTML");System.out.println("Diretorio 'HTML' criado");}
    if (!mp.verificaArquivoExiste("HTML/Manual_JProvas.pdf")){mp.extrairRecursoJar("/Recursos/","Manual_JProvas.pdf","HTML/");System.out.println("Arquivo 'HTML/Manual_JProvas.pdf' criado");}
    mp.abrirArquivo("HTML/Manual_JProvas.pdf");
  }//GEN-LAST:event_itemMenu_ManualActionPerformed

private void encerrarSistema(){
    System.out.println("Encerrando o JProvas...");
    //Fechar abas abertas
    subtelaPainelArvore2.fecharAbas();
    //Desfragmentar arquivo de banco de dados
    DesfragmentadorBanco sistem = new DesfragmentadorBanco();
    sistem.banco1= subtelaPainelArvore2.conexao;
    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    sistem.verificaFragmentacaoMDB();
    this.setCursor(Cursor.getDefaultCursor());
    //Encerrar o sistema
    this.dispose();
}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu itemMenu_Configuracoes;
  private javax.swing.JMenuItem itemMenu_Desfragmentar;
  private javax.swing.JMenuItem itemMenu_Manual;
  private javax.swing.JMenuItem itemMenu_Preferencias;
  private javax.swing.JMenuItem itemMenu_Sair;
  private javax.swing.JMenuItem itemMenu_Sobre;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  public javax.swing.JLabel jlabInformativaRodape;
  public final javax.swing.JTabbedPane painelJtab = new javax.swing.JTabbedPane();
  private static final Telas.SubtelaPainelArvore subtelaPainelArvore2 = new Telas.SubtelaPainelArvore();
  // End of variables declaration//GEN-END:variables
}
