/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo
 */
public class SubTelaPreferenciasDiretorio extends javax.swing.JPanel {

  String diretorioAtualImg="";
  String diretorioAtualProva="";
  
  JFileChooser jf = new JFileChooser();
  
  public SubTelaPreferenciasDiretorio() {
    if(JProvas.JProvas_DAOquestao.obtemDiretorioImagens()!=null){diretorioAtualImg=JProvas.JProvas_DAOquestao.obtemDiretorioImagens();}
    if(JProvas.JProvas_DAOProva.consultaParametroSistema(8)!=null){diretorioAtualProva=JProvas.JProvas_DAOProva.consultaParametroSistema(8);}
    initComponents();
    campoDirImgQuest.setText(diretorioAtualImg);
    campoDirImgProva.setText(diretorioAtualProva);
    jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    jf.setAcceptAllFileFilterUsed(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    campoDirImgQuest = new javax.swing.JTextField();
    btSelecao2 = new javax.swing.JButton();
    btApagar2 = new javax.swing.JButton();
    btSalvar = new javax.swing.JButton();
    btCancelar = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    campoDirImgProva = new javax.swing.JTextField();
    btSelecao1 = new javax.swing.JButton();
    btApagar1 = new javax.swing.JButton();

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    jButton1.setText("Salvar");

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    jButton2.setText("Cancelar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Diretório de Imagens das Questoes:"));

    campoDirImgQuest.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    campoDirImgQuest.setEnabled(false);

    btSelecao2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    btSelecao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesSistema/pastaFechada.gif"))); // NOI18N
    btSelecao2.setText("Selecionar");
    btSelecao2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSelecao2ActionPerformed(evt);
      }
    });

    btApagar2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    btApagar2.setText("Apagar");
    btApagar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btApagar2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(campoDirImgQuest)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btApagar2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btSelecao2)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(campoDirImgQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btSelecao2)
          .addComponent(btApagar2)))
    );

    btSalvar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    btSalvar.setText("Salvar");
    btSalvar.setEnabled(false);
    btSalvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSalvarActionPerformed(evt);
      }
    });

    btCancelar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    btCancelar.setText("Cancelar");
    btCancelar.setEnabled(false);
    btCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btCancelarActionPerformed(evt);
      }
    });

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Diretório de Imagens das Provas:"));

    campoDirImgProva.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    campoDirImgProva.setEnabled(false);

    btSelecao1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    btSelecao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesSistema/pastaFechada.gif"))); // NOI18N
    btSelecao1.setText("Selecionar");
    btSelecao1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSelecao1ActionPerformed(evt);
      }
    });

    btApagar1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    btApagar1.setText("Apagar");
    btApagar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btApagar1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(campoDirImgProva)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btApagar1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btSelecao1)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(23, Short.MAX_VALUE)
        .addComponent(campoDirImgProva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btSelecao1)
          .addComponent(btApagar1)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 209, Short.MAX_VALUE)
            .addComponent(btSalvar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btCancelar)))
        .addContainerGap())
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap()))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(137, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(86, 86, 86)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btSalvar)
          .addComponent(btCancelar))
        .addGap(26, 26, 26))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(249, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
    campoDirImgQuest.setText(JProvas.JProvas_DAOquestao.obtemDiretorioImagens());
    campoDirImgProva.setText(JProvas.JProvas_DAOProva.consultaParametroSistema(8));
    btSalvar.setEnabled(false);
    btCancelar.setEnabled(false);
  }//GEN-LAST:event_btCancelarActionPerformed

  private void btApagar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagar2ActionPerformed
    campoDirImgQuest.setText("");
    if(campoDirImgQuest.getText().compareTo(diretorioAtualImg)!=0){
      btSalvar.setEnabled(true);
      btCancelar.setEnabled(true);
    }
  }//GEN-LAST:event_btApagar2ActionPerformed

  private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
    String texto = "";
    //gravar imagem questao
    if(campoDirImgQuest.getText()!=null){texto=campoDirImgQuest.getText();}
    if(campoDirImgQuest.getText().compareTo(diretorioAtualImg)!=0){
    diretorioAtualImg=campoDirImgQuest.getText();
    atualizaBanco(diretorioAtualImg, 7);
    }
    //gravar  imagem prova
    if(campoDirImgProva.getText()!=null){texto=campoDirImgProva.getText();}
    if(campoDirImgProva.getText().compareTo(diretorioAtualProva)!=0){
    diretorioAtualProva=campoDirImgProva.getText();
    atualizaBanco(diretorioAtualProva, 8);
    }
    btSalvar.setEnabled(false);
    btCancelar.setEnabled(false);
  }//GEN-LAST:event_btSalvarActionPerformed

  private void btSelecao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecao2ActionPerformed
    int retornoChooser=jf.showOpenDialog(this);
    if (retornoChooser == jf.APPROVE_OPTION) {
      try {
        diretorioAtualImg=jf.getSelectedFile().getCanonicalPath();
      } catch (IOException ex) {
        JOptionPane.showMessageDialog(null,"Erro na funcao btSelecao2ActionPerformed da classe SubTelaPreferenciasDiretorio" + ex.getMessage(),"Erro",0);
      }
      campoDirImgQuest.setText(diretorioAtualImg);
      btSalvar.setEnabled(true);
      btCancelar.setEnabled(true);
    }
  }//GEN-LAST:event_btSelecao2ActionPerformed

  private void btSelecao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecao1ActionPerformed
    int retornoChooser=jf.showOpenDialog(this);
    if (retornoChooser == jf.APPROVE_OPTION) {
      try {
       // diretorioAtualProva=jf.getSelectedFile().getCanonicalPath();
        campoDirImgProva.setText(jf.getSelectedFile().getCanonicalPath());
      } catch (IOException ex) {
        JOptionPane.showMessageDialog(null,"Erro na funcao btSelecao1ActionPerformed da classe SubTelaPreferenciasDiretorio" + ex.getMessage(),"Erro",0);
      }
      //campoDirImgProva.setText(diretorioAtualProva);
      btSalvar.setEnabled(true);
      btCancelar.setEnabled(true);
    }
  }//GEN-LAST:event_btSelecao1ActionPerformed

  private void btApagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagar1ActionPerformed
    campoDirImgProva.setText("");
    if(campoDirImgProva.getText().compareTo(diretorioAtualProva)!=0){
      btSalvar.setEnabled(true);
      btCancelar.setEnabled(true);
    }
  }//GEN-LAST:event_btApagar1ActionPerformed

  public void atualizaBanco(String texto, int nuParametro){
    JProvas.conexaoJProvas.executaSQLsemRetorno("update TB08_SISTEMA set valor_parametro='"+texto+"' where nu_parametro="+nuParametro);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btApagar1;
  private javax.swing.JButton btApagar2;
  private javax.swing.JButton btCancelar;
  private javax.swing.JButton btSalvar;
  private javax.swing.JButton btSelecao1;
  private javax.swing.JButton btSelecao2;
  private javax.swing.JTextField campoDirImgProva;
  private javax.swing.JTextField campoDirImgQuest;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
