/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.CardLayout;
import javax.swing.Icon;
import javax.swing.JPanel;

/**
 *
 * @author Danilo
 */
public class TelaPreferencias extends javax.swing.JDialog {
    
    public static boolean alteracoes_naoSalvas_tela1=false;
    Icon iconeSelecao = new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesSistema/btSelecaoHoriz.gif"));
    SubTelaPreferenciasProva telaProva = new SubTelaPreferenciasProva();
    SubTelaPreferenciasDiretorio telaDiretorios = new SubTelaPreferenciasDiretorio();
    CardLayout cl;
    
    public TelaPreferencias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        //JCard_1.
        initComponents();
        JCard_1.add(telaProva,"t1");
        JCard_1.add(telaDiretorios,"t2");
        cl = (CardLayout)(JCard_1.getLayout());
        cl.show(JCard_1, "t1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator1 = new javax.swing.JSeparator();
    labelSelectProva = new javax.swing.JLabel();
    JCard_1 = new JPanel(new CardLayout());
    labelSelectDiretorio = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Preferencias JProvas");
    setResizable(false);

    jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

    labelSelectProva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelSelectProva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesSistema/btSelecaoHoriz.gif"))); // NOI18N
    labelSelectProva.setText("Prova");
    labelSelectProva.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelSelectProvaMouseClicked(evt);
      }
    });

    JCard_1.setLayout(new java.awt.CardLayout());

    labelSelectDiretorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelSelectDiretorio.setText("Diretórios");
    labelSelectDiretorio.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelSelectDiretorioMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelSelectProva)
          .addComponent(labelSelectDiretorio))
        .addGap(58, 58, 58)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(JCard_1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(labelSelectProva)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelSelectDiretorio)
        .addContainerGap(348, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(JCard_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void labelSelectDiretorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSelectDiretorioMouseClicked
    alteraIconeSelecao(2);
    cl.show(JCard_1, "t2");
  }//GEN-LAST:event_labelSelectDiretorioMouseClicked

  private void labelSelectProvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSelectProvaMouseClicked
    alteraIconeSelecao(1);
    cl.show(JCard_1, "t1");
  }//GEN-LAST:event_labelSelectProvaMouseClicked

  public void alteraIconeSelecao(int i){
    switch(i){
      case 1:{labelSelectProva.setIcon(iconeSelecao);
              labelSelectDiretorio.setIcon(null);
              return;
      }
      case 2:{labelSelectProva.setIcon(null);
              labelSelectDiretorio.setIcon(iconeSelecao);
              return;
      }
    }
  }
  
    /**
     * @param args the command line arguments
     */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel JCard_1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel labelSelectDiretorio;
  private javax.swing.JLabel labelSelectProva;
  // End of variables declaration//GEN-END:variables
}
