/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Danilo
 */
public class TelaRenomearItem extends javax.swing.JDialog {

  SubtelaPainelArvore pArvore;
  String operacao;
  SubtelaEditorProva sbtEditProvaTelaRenomear;
  
  public TelaRenomearItem(java.awt.Frame parent, boolean modal, SubtelaPainelArvore p, String operacao) {
    super(parent, modal);
    initComponents();
    pArvore = p;
    this.operacao = operacao;
    switch(operacao){
      case "renomear":{
        LabelOperacao.setText("Renomear ítem: Digite o novo nome");
        break;
      }
      case "novaProva":{
        LabelOperacao.setText("Nova Prova: Digite um titulo para a nova Prova");
        break;
      }
      case "novaQuestao":{
        LabelOperacao.setText("Nova Questão: Digite um titulo para a nova Questao");
        break;
      }
      case "novaCategoria":{
        LabelOperacao.setText("Nova Categoria: Digite um titulo para a nova Categoria");
        break;
      }  
    }
    this.setVisible(true);
  }

  public TelaRenomearItem(java.awt.Frame parent, boolean modal,SubtelaEditorProva o){
    super(parent, modal);
    initComponents();
    sbtEditProvaTelaRenomear = o;
    LabelOperacao.setText("Nova Divisoria: Digite o texto");
    operacao = "novaDivisoria";
    this.setVisible(true);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    LabelOperacao = new javax.swing.JLabel();
    fieldNovoNome = new javax.swing.JTextField();
    btOk = new javax.swing.JButton();
    btCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    LabelOperacao.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
    LabelOperacao.setText("OPERAÇÃO A EXECUTAR");

    btOk.setText("OK");
    btOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btOkActionPerformed(evt);
      }
    });

    btCancelar.setText("CANCELAR");
    btCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(LabelOperacao)
              .addComponent(fieldNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGap(57, 57, 57)
            .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(55, 55, 55)
            .addComponent(btCancelar)))
        .addContainerGap(42, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(LabelOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(fieldNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(47, 47, 47)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btOk)
          .addComponent(btCancelar))
        .addContainerGap(39, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
    if(fieldNovoNome.getText().compareTo("")!=0){
      switch(operacao){
        case "renomear":{
          pArvore.acionaRenomear(fieldNovoNome.getText());
          break;
        }
        case "novaProva":{
          pArvore.acionaCriarNovaProva(fieldNovoNome.getText());
          break;
        }
        case "novaQuestao":{
          pArvore.acionaCriarNovaQuestao(fieldNovoNome.getText());
          break;
        }
        case "novaCategoria":{
          pArvore.acionaCriarNovaCategoria(fieldNovoNome.getText());
          break;
        }
        case "novaDivisoria":{
          if(!fieldNovoNome.getText().isEmpty()){
            sbtEditProvaTelaRenomear.adicionarDivisoria(fieldNovoNome.getText());
            //sbtEditProvaTelaRenomear.nuItensLinha++;
          }
          break;
        }
      }
      this.dispose();
    }
  }//GEN-LAST:event_btOkActionPerformed

  
  private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_btCancelarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel LabelOperacao;
  private javax.swing.JButton btCancelar;
  private javax.swing.JButton btOk;
  private javax.swing.JTextField fieldNovoNome;
  // End of variables declaration//GEN-END:variables
}
